### ISSUE TITLE
CSS bug: Cannot Read white link text on light grey background

### ISSUE THREAD

**Issue by decause** [ryansb/ofCourse#51]
![screenshot from 2015-08-20 14-22-12](https://cloud.githubusercontent.com/assets/427420/9391823/2021a760-4747-11e5-87ba-7df613a18e08.png)

See above screenshot on http://hfoss-ritigm.rhcloud.com/hw/bugfix for example. White text on light grey background = difficult to read.

@mellolikejello perhaps would have some advice for an easy-fix contribution by a new student this semester?

**Comment by mellolikejello** [comment]
The easiest fix would be to change the white text to black or to the background color (blue in this case).

 A more involved but better material design option would be to match the card style (http://www.google.com/design/spec/components/cards.html), and add a small color border to preserve the color differentiator between note(green) and task(blue). The red/orange warnings should be fine the way they are. 

Then, the highlighted text should have a light color background (http://fezvrasta.github.io/bootstrap-material-design/#material-colors << a lighter shade of indigo to match the header would be ideal) with white text.

**Comment by ryansb** [comment]
@mellolikejello would you be able to make this CSS change? If so, I can assign this to you.

**Comment by decause** [comment]
@ryansb this is an excellent easyfix bug. Perhaps we can leave it as an
exercise for new hfoss contributors?

**Comment by ryansb** [comment]
Indeed it is - when is the first bugfix assignment?

**Comment by decause** [comment]
Usually week 2 or 3, but it's not my syllabus this time around ;)

**Comment by sctjkc01** [comment]
/me facepalms - why is it that the one file I need to patch is minified... and is a single line of over a million characters?

**Comment by ryansb** [comment]
Probably because it's a library, and you shouldn't change it. Instead, I'd recommend overriding it in https://github.com/ryansb/ofCourse/blob/develop/ofcourse/static/css/site.css

**Comment by sctjkc01** [comment]
Hm.  The thing is, Chrome's reading that the `material-wfont.min.css` sheet is trying to override the `site.css` sheet (as opposed to the other way around).  In theory, this might be because we load `material-wfont` before `site` - perhaps switching the two around in the header (ie, loading `site` before `material-wfont`) might fix this?

**Comment by sctjkc01** [comment]
Okay, now that I finally properly understand how CSS rules are applied:

Given the same selector, the sheet loaded last is the one that takes precedence, sure.  Thereby `site` should come after `material-wfont`.  However, because `material-wfont` has a more specific selector that matches the section (it captures `.alert a` as opposed to just `a` like `site` does), Chrome gives that more precedence.

Knowing that, it becomes a simple matter of defining a rule for `.alert a` in `site` and calling it good, however the issue then becomes how to make it generic enough that it captures everything.  And even then, I can forsee `.alert a` also capturing links that are just naked in the an alert box - at that point the rule needs to be `.alert code>a`...

**Comment by ryansb** [comment]
Ok, so `.alert code>a` sounds like a reasonable solution, would you like to post a patch for that?

**Comment by sctjkc01** [comment]
So sctjkc01/ofCourse@1e8ebf0 should fix one of the two issues, namely fix the link text color:

![1e8ebf0](https://cloud.githubusercontent.com/assets/1090204/9893694/84a08ec0-5be9-11e5-89e9-4caf06f89ffa.png)

Now I'm going to try to figure out how best to fix paragraphs.  I think making them black would be good, but figuring out how to do it in a general way via CSS alone on `site.css` is what's puzzling me atm...

**Comment by sctjkc01** [comment]
Excellent.  sctjkc01/ofCourse@232cc89 fixes the non-link text coloration:

![image](https://cloud.githubusercontent.com/assets/1090204/9893968/92674492-5bec-11e5-9dfe-4d395cc65346.png)

The path currently assumes that anyone using any of `.alert-{info|success|warning|failure}` is putting it on a `div` along with the `.alert` class.  Therefore, anything just using `.alert` gets the slightly-gray `#333` coloration, while those that should be white are white.
